const PROVINCES = [
    {name:'Álava'},
    {name:'Albacete'},
    {name:'Alicante'},
    {name:'Almería'},
    {name:'Asturias'},
    {name:'Ávila'},
    {name:'Badajoz'},
    {name:'Barcelona'},
    {name:'Burgos'},
    {name:'Cáceres'},
    {name:'Cádiz'},
    {name:'Cantabria'},
    {name:'Castellón'},
    {name:'Ciudad Real'},
    {name:'Córdoba'},
    {name:'La Coruña'},
    {name:'Cuenca'},
    {name:'Gerona'},
    {name:'Granada'},
    {name:'Guadalajara'},
    {name:'Lugo'},
    {name:'Madrid'},
    {name:'Málaga'},
    {name:'Murcia'},
    {name:'Navarra'},
    {name:'Segovia'},
    {name:'Sevilla'},
    {name:'Soria'},
    {name:'Tarragona'},
    {name:'Vizcaya'},
    {name:'Zamora'},
    {name:'Zaragoza'}
]

export default PROVINCES