const PROVINCES = [
    {name:'Álava'},
    {name:'Albacete'},
    {name:'Alicante'},
    {name:'Almería'},
    {name:'Asturias'},
    {name:'Ávila'},
    {name:'Badajoz'},
    {name:'Barcelona'},
    {name:'Burgos'},
    {name:'Cáceres'},
    {name:'Cádiz'},
    {name:'Cantabria'},
    {name:'Castellón'},
    {name:'Ciudad Real'},
    {name:'Córdoba'},
    {name:'Cuenca'},
    {name:'Gerona'},
    {name:'Granada'},
    {name:'Guadalajara'},
    {name:'Guipúzcoa'},
    {name:'Huelva'},
    {name:'Huesca'},
    {name:'Islas Baleares'},
    {name:'Jaén'},
    {name:'La Coruña'},
    {name:'La Rioja'},
    {name:'Las Palmas'},
    {name:'León'},
    {name:'Lérida'},
    {name:'Lugo'},
    {name:'Madrid'},
    {name:'Málaga'},
    {name:'Murcia'},
    {name:'Navarra'},
    {name:'Orense'},
    {name:'Palencia'},
    {name:'Pontevedra'},
    {name:'Salamanca'},
    {name:'Santa Cruz de Tenerife'},
    {name:'Segovia'},
    {name:'Sevilla'},
    {name:'Soria'},
    {name:'Tarragona'},
    {name:'Teruel'},
    {name:'Toledo'},
    {name:'Valencia'},
    {name:'Valladolid'},
    {name:'Vizcaya'},
    {name:'Zamora'},
    {name:'Zaragoza'}
]

export default PROVINCES